#!/usr/bin/env ruby

require File.dirname(__FILE__) + "/../config/environment"
require "rubygems"
require "colored"

def execute(sql)
  extend ActionView::Helpers::TextHelper
  
#   puts "* Executing SQL: #{truncate(sql, 100)}"
  result = ActiveRecord::Base.connection.execute(sql)
  result.extend Enumerable
  result.to_a
end

tables = execute "SHOW TABLES"
tables = tables.map { |t| t.first }

tables.each do |table|
  schema = execute("SHOW CREATE TABLE #{table}")[0][1]

  if schema =~ /COLLATE=(.*)/
    puts "#{table} collation: #{$1}".red
  else
    puts "#{table}: No collation found".green
  end
end

